### ISSUE TITLE
The GAMA luminosities don't carry a unit

### ISSUE THREAD

**Issue by Moyoxkit** [SWIFTSIM/SOAP#10]
In the current version of SOAP, the GAMA luminosities defined for the stars don't carry a unit, while they could just carry erg/s. You can see this here:
https://github.com/SWIFTSIM/SOAP/blob/6100ac87250defb5d1cb04368cce3dbd7d111147/aperture_properties.py#L217

**Comment by Moyoxkit** [comment]
Update to this, it makes sense that there is no unit for stellar luminosities, as they have their own defined dimensionless unit within SWIFT, see image below. It would however be good to add this information as a footnote to the SOAP documentation.

<img width="914" alt="Screenshot 2023-03-21 at 15 21 59" src="https://user-images.githubusercontent.com/37077325/226637142-bc53cae6-3db8-4264-a9f1-31e6941ec7aa.png">

**Comment by MatthieuSchaller** [comment]
It is inconsistent, yes. 

The problem that to be consistent we'd have to convert to what ever Jy is in our internal system of units and that then leads to all kinds of very unusual unit corrections throughout all the pipelines.

**Comment by MatthieuSchaller** [comment]
Can we push this to the docs?
