### ISSUE TITLE
BUG: SOAP `compute_halo_properties.py` always aborts when no FoF file found

### ISSUE THREAD

**Issue by james-trayford** [SWIFTSIM/SOAP#110]
Running SOAP on test runs using VR instead of HBT structure finding was failing because of no FoF file being found - IIUC this should still be appropriate to run in the non-HBT case where there is no FoF file. 

Found the conditional:

https://github.com/SWIFTSIM/SOAP/blob/e1f14acb5fd362a2a8e774962a931834b654a13c/soap_args.py#L160-L162

is always executed, even in non-HBT case, resulting in abort. commenting this out led to successful running.

can we add the condition tha3t this only aborts here in the HBT case?

**Comment by robjmcgibbon** [comment]
Thanks James, I've put a fix in https://github.com/SWIFTSIM/SOAP/pull/111. If the FOF filename is not set in the parameter file then the check will be skipped
