### ISSUE TITLE
Compute centre of mass velocity of stars in apertures

### ISSUE THREAD

**Issue by jchelly** [SWIFTSIM/SOAP#28]
Currently we compute the centre of mass position and velocity of the particles in each aperture. The apertures are centred on the potential minimum output by VR and we compute the mass weighted mean position and velocity of the particles within the aperture. All particle types are included in this calculation.

It would be useful to have the velocity of just the star particles too. We would compute the mass weighted mean velocity (and maybe also position?) of just the stars in each aperture and output that as a new halo property.

**Comment by robjmcgibbon** [comment]
Is this not already being calculated [here](https://github.com/SWIFTSIM/SOAP/blob/d4bcf0d21e8ca4127d728b944fc25d35d0a7144f/aperture_properties.py#L516)?
