### ISSUE TITLE
Rockstar support

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/SOAP#33]
We should try to read in Rockstar files and produce a catalog from there. 

@kyleaoman mentioned he may have some old reading script. Maybe there is something there that can be used. Key bit is understanding the membership files and the subhalo <-> parent halo connection.

**Comment by kyleaoman** [comment]
This is what I have, it's for the merger trees, not the halo catalogues. Looks like it's Peter's code, I might have wrapped it in Python? Been a long while (10 years?) https://github.com/kyleaoman/read_tree

At some point I also modified rockstar just to change the search radius within which subhalos are assigned to halos (later switched to a much simpler solution to the same question I was trying to answer at the time). That's at https://github.com/kyleaoman/rockstar, I guess if you want a quick pointer to where the parent-subhalo connection is created you can look at the one (?) commit by me on that repo. Again this was ages ago, I assume that the rockstar code has probably changed somewhat in the meantime!
