### ISSUE TITLE
Colibre parameter file out of date?

### ISSUE THREAD

**Issue by FHusko** [SWIFTSIM/SOAP#86]
I think the parameter file for Colibre might be out of date: `parameter_files/colibre_SOAP_params.yml`.

The latest version of the pipeline tries to use quantities that seem to not be saved in the SOAP catalogues. For example:

`'CatalogueGroup_ExclusiveSphere_50kpc' object has no attribute 'gasmassincolddensediffusemetals'`

In the parameter file itself, this is explicitly set to not be recorded:
`GasMassInColdDenseDiffuseMetals: false`

I suspect there are other fields that are inconsistent.

**Comment by robjmcgibbon** [comment]
Thanks for this. Which other fields do you think might be inconsistent? Is there anything else that's breaking the pipeline?

**Comment by FHusko** [comment]
I may be entirely wrong about other fields being inconsistent! I was just guessing based on the fact that there were new chemistry-related plots but no new updates to the SOAP parameter file in the last 4 months.

**Comment by robjmcgibbon** [comment]
>In the parameter file itself, this is explicitly set to not be recorded:
GasMassInColdDenseDiffuseMetals: false

Fixed in https://github.com/SWIFTSIM/SOAP/pull/88

> I may be entirely wrong about other fields being inconsistent! I was just guessing based on the fact that there were new chemistry-related plots but no new updates to the SOAP parameter file in the last 4 months.

Cool, closing this issue then
